### ISSUE TITLE
Upon install: `parseInputs': undefined method `gsub' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ptmkenny** [iandol/scrivomatic#15] opened 2018-05-25 16:34 UTC
I just downloaded the files, unzipped them, put them in ~/bin, and then ran `chmod 755 scrivomatic`.

Now, when I try to run scrivomatic, I get this error:

> /Users/pk/bin/scrivomatic:130:in `parseInputs': undefined method `gsub' for nil:NilClass (NoMethodError)

I have no idea what it means.

I'm running macOS 10.13.4, and I just installed brew/pandoc/pandocomatic today, so they are the latest versions as of May 25.

Any help would be much appreciated.

**Comment by iandol** [comment] 2018-06-02 14:38
hm, can you tell me what the exact input to scrivomatic is (the full log may help), are you using it via scrivener or from the command line?

**Comment by iandol** [comment] 2018-07-16 16:07
we can't reproduce this, so lets close it...

**Closed by iandol** 2018-07-16 16:07 UTC
